config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :publications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "publications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/publication.rb
class Publication < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :publications

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all.order("created_at DESC")
    @publication = Publication.new
    #if we don't add this code, ERROR shown "undefined method `model_name' for nil:NilClass"
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = current_user.publications.build
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = current_user.publications.build(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to root_path, notice: 'publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:publication)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end


	def acount_update_params
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceCloneRubyOnRailsProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>

    <nav class="navbar is-info">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Twittter</h1>
          <% end %>
          <div class="navbar-burger burger" data-target="navbarExample">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>

   

<div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'New publication', root_path, class: "button is-info is-inverted" %>
            </p>
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
            <p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/publications/_feed.html.erb
<div class="column is-half">
	<% if user_signed_in? %>
	<article class="media box">
		<figure class="media-left">
			<p class="image is-64X64">
			<!--	<img src="https://steemitimages.com/DQmTeuJCgWJ9ikZtLD1Ey66qdois2mgbSQyFgcVXf6xPnK7/icon.png">  -->
				<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
			</p>
		</figure>
		<div class="media-content">
			 <%= render 'publications/form' %>
		</div>
	</article>
	<% end %>

<% @publications.each do | publication | %>
	<div class="box">
		<article class="media">
			<div class="media-left">
				<figure class="image is-64X64">
				<!--	<img src="https://steemitimages.com/DQmTeuJCgWJ9ikZtLD1Ey66qdois2mgbSQyFgcVXf6xPnK7/icon.png">  -->
					<%= gravatar_image_tag(publication.user.email, size: 64, alt: publication.user.name) %>
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<strong><%= publication.user.name %></strong><br />
					<small><%= publication.user.username %></small><br />
					<p><%= publication.publication %></p>
				</div>

				<nav class="level">
	  				<div class="level-left is-mobile">
	  					<%= link_to publication, class: "level-item" do %>
	  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
	  					<% end %>
		  				<%= link_to edit_publication_path(publication), class: "level-item" do %>
	  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
	  					<% end %>
	  					<%= link_to publication, method: :delete, data: { confirm: "Are you sure you want to delete this publication?" } do %>
	  						<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
	  					<% end %>
	  				</div>
  				</nav>

			</div>
		</article>
	</div>
  <% end %>
</div>

app/views/publications/_form.html.erb
<%= simple_form_for(@publication) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :publication, label: "Publication about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new publication...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/publications/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
					<!--	<img src="https://steemitimages.com/DQmNnAYTuBy85wVpwZGrcdp7BVRmWCMpTZaHs46tdq3EtRn/cutmypic.png">  -->
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>

				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Publications</p>
						<p class="title is-6"><%= current_user.publications.count %></p>
					</div>
				</div>

				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">250</p>
					</div>
				</div>

				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">500K</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/publications/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			Trend 1
		</a>
		<a class="panel-block">
			Trend 2
		</a>
		<a class="panel-block">
			Trend 3
		</a>
		<a class="panel-block">
			Trend 4
		</a>
		<a class="panel-block">
			Trend 5
		</a>
		<a class="panel-block">
			Trend 6
		</a>
	</nav>
</div>

app/views/publications/_who-to-follow.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Who to Follow</p>
	
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Biplob World</strong>
						<small>@marketerbiplob</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Biplob World</strong>
						<small>@marketerbiplob</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Biplob World</strong>
						<small>@marketerbiplob</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	</nav>
</div>

app/views/publications/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Publication</h1>
				<%= render 'form', publication: @publication %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', publications_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/publications/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
    <% if user_signed_in? %>
    	<%= render 'profile' %>
    <% else %>
      <%= render 'trends' %>
     <% end %>
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/publications/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Publication</h1>
					<%= render 'form', publication: @publication %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', publications_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Publication:</strong>
  <%= @publication.publication %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>

app/views/tweeets/_feed.html.erb
<div class="column is-half">
	<% if user_signed_in? %>
	<article class="media box">
		<figure class="media-left">
			<p class="image is-64X64">
			<!--	<img src="https://steemitimages.com/DQmTeuJCgWJ9ikZtLD1Ey66qdois2mgbSQyFgcVXf6xPnK7/icon.png">  -->
				<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
			</p>
		</figure>
		<div class="media-content">
			 <%= render 'tweeets/form' %>
		</div>
	</article>
	<% end %>

<% @tweeets.each do | tweeet | %>
	<div class="box">
		<article class="media">
			<div class="media-left">
				<figure class="image is-64X64">
				<!--	<img src="https://steemitimages.com/DQmTeuJCgWJ9ikZtLD1Ey66qdois2mgbSQyFgcVXf6xPnK7/icon.png">  -->
					<%= gravatar_image_tag(tweeet.user.email, size: 64, alt: tweeet.user.name) %>
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<strong><%= tweeet.user.name %></strong><br />
					<small><%= tweeet.user.username %></small><br />
					<p><%= tweeet.tweeet %></p>
				</div>

				<nav class="level">
	  				<div class="level-left is-mobile">
	  					<%= link_to tweeet, class: "level-item" do %>
	  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
	  					<% end %>
		  				<%= link_to edit_tweeet_path(tweeet), class: "level-item" do %>
	  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
	  					<% end %>
	  					<%= link_to tweeet, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" } do %>
	  						<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
	  					<% end %>
	  				</div>
  				</nav>

			</div>
		</article>
	</div>
  <% end %>
</div>

app/views/tweeets/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
					<!--	<img src="https://steemitimages.com/DQmNnAYTuBy85wVpwZGrcdp7BVRmWCMpTZaHs46tdq3EtRn/cutmypic.png">  -->
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>

				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweeets</p>
						<p class="title is-6"><%= current_user.tweeets.count %></p>
					</div>
				</div>

				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">250</p>
					</div>
				</div>

				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">500K</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/tweeets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweeet</h1>
				<%= render 'form', tweeet: @tweeet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweeets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweeets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Tweeet</h1>
					<%= render 'form', tweeet: @tweeet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweeets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>